// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUdk3pT127JwPF28wQkywvZ-o9O9Ijz9s',
    appId: '1:828972046002:web:3f4c72c796de9e8f305bab',
    messagingSenderId: '828972046002',
    projectId: 'lingo007',
    authDomain: 'lingo007.firebaseapp.com',
    databaseURL: 'https://lingo007-default-rtdb.firebaseio.com',
    storageBucket: 'lingo007.appspot.com',
    measurementId: 'G-4C5Y7Y3W5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj09pm5uk6j3L-mSjrYdbpXGja2sToM-c',
    appId: '1:828972046002:android:c7300bd65fa3fc73305bab',
    messagingSenderId: '828972046002',
    projectId: 'lingo007',
    databaseURL: 'https://lingo007-default-rtdb.firebaseio.com',
    storageBucket: 'lingo007.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmBVepMLxSfh6fHx0FzfGDOtxx8hYDdno',
    appId: '1:828972046002:ios:41016ca8f30b6588305bab',
    messagingSenderId: '828972046002',
    projectId: 'lingo007',
    databaseURL: 'https://lingo007-default-rtdb.firebaseio.com',
    storageBucket: 'lingo007.appspot.com',
    iosBundleId: 'com.example.prokat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmBVepMLxSfh6fHx0FzfGDOtxx8hYDdno',
    appId: '1:828972046002:ios:41016ca8f30b6588305bab',
    messagingSenderId: '828972046002',
    projectId: 'lingo007',
    databaseURL: 'https://lingo007-default-rtdb.firebaseio.com',
    storageBucket: 'lingo007.appspot.com',
    iosBundleId: 'com.example.prokat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu49h8VrfgsPuvvr3hso2C3lDhksRunBE',
    appId: '1:828972046002:web:798daee7cac7c44d305bab',
    messagingSenderId: '828972046002',
    projectId: 'lingo007',
    authDomain: 'lingo007.firebaseapp.com',
    databaseURL: 'https://lingo007-default-rtdb.firebaseio.com',
    storageBucket: 'lingo007.appspot.com',
    measurementId: 'G-F00QGCK09K',
  );
}
