// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXMCkdY4sdQJ_yvCI6ZzPd_92tu9SKQHI',
    appId: '1:1074557540622:web:56f44de9257331d8845f5f',
    messagingSenderId: '1074557540622',
    projectId: 'prokat-bfbec',
    authDomain: 'prokat-bfbec.firebaseapp.com',
    storageBucket: 'prokat-bfbec.firebasestorage.app',
    measurementId: 'G-EV9JFVT6Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcDXeCUa8yPJ7wSBpvgGJNkBImm2IzSGQ',
    appId: '1:1074557540622:android:b034923095bf433d845f5f',
    messagingSenderId: '1074557540622',
    projectId: 'prokat-bfbec',
    storageBucket: 'prokat-bfbec.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkXL7H5f1hc_7WoYzDuwSgD4ri5czYe1E',
    appId: '1:1074557540622:ios:77d941fb94c43410845f5f',
    messagingSenderId: '1074557540622',
    projectId: 'prokat-bfbec',
    storageBucket: 'prokat-bfbec.firebasestorage.app',
    iosBundleId: 'com.auyltech.prokat',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkXL7H5f1hc_7WoYzDuwSgD4ri5czYe1E',
    appId: '1:1074557540622:ios:0083c05261f99dbd845f5f',
    messagingSenderId: '1074557540622',
    projectId: 'prokat-bfbec',
    storageBucket: 'prokat-bfbec.firebasestorage.app',
    iosBundleId: 'com.example.prokat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXMCkdY4sdQJ_yvCI6ZzPd_92tu9SKQHI',
    appId: '1:1074557540622:web:29bf672e4cf6ad8b845f5f',
    messagingSenderId: '1074557540622',
    projectId: 'prokat-bfbec',
    authDomain: 'prokat-bfbec.firebaseapp.com',
    storageBucket: 'prokat-bfbec.firebasestorage.app',
    measurementId: 'G-KVT6GXL514',
  );
}
